/**
 * Generated by X337
 *
 * Source:
 * unknown
 *
 * Origin:
 * unknown
 */


interface CommandPaletteProps {


  children?: React.ReactNode;

}


export default function CommandPalette(
{

  children,

}: CommandPaletteProps
) {


  return (

    <div
      className="CommandPalette"
    >

      {children}

    </div>

  );

}