/**
 * Generated by X337
 *
 * Source:
 * unknown
 *
 * Origin:
 * unknown
 */


interface DataTableProps {


  children?: React.ReactNode;

}


export default function DataTable(
{

  children,

}: DataTableProps
) {


  return (

    <div
      className="DataTable"
    >

      {children}

    </div>

  );

}