
import React from "react";

import TaskPlanner
    from "../components/TaskPlanner";

export default function Practice() {

    return (

        <section>

            <h2>
                Practice
            </h2>

            <p>
                Personalized practice generated by X337.
            </p>

            <TaskPlanner />

        </section>

    );
}
