from core.generator.file_generator import FileGenerator


class ProjectGenerator:

    def __init__(self):
        self.file_generator = FileGenerator()

    def generate(self, project):

        raw_name = (
            project.get(
                "project",
                "X337 Generated Project"
            )
            .strip()
        )

        safe_name = self.file_generator._safe_name(raw_name)

        files = {

            "package.json": r'''
{
  "name": "x337-generated-project",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@vitejs/plugin-react": "latest",
    "vite": "latest",
    "typescript": "latest",
    "react": "latest",
    "react-dom": "latest"
  },
  "devDependencies": {}
}
''',

            "index.html": r'''
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>X337 Generated Application</title>
  </head>

  <body>
    <div id="root"></div>

    <script
      type="module"
      src="/src/main.tsx">
    </script>
  </body>
</html>
''',

            "vite.config.ts": r'''
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
    plugins: [react()]
});
''',

            "src/main.tsx": r'''
import React from "react";
import ReactDOM from "react-dom/client";

import App from "./App";

ReactDOM.createRoot(
    document.getElementById("root")!
).render(
    <React.StrictMode>
        <App />
    </React.StrictMode>
);
''',

            "src/App.tsx": f'''
import React from "react";

import Dashboard from "./pages/Dashboard";
import Practice from "./pages/Practice";
import Profile from "./pages/Profile";

export default function App() {{

    return (
        <div
            style={{{{
                minHeight: "100vh",
                padding: "40px",
                fontFamily: "Inter, sans-serif",
                background: "#f5f7fb"
            }}}}
        >

            <h1>
                {raw_name}
            </h1>

            <Dashboard />

            <Practice />

            <Profile />

        </div>
    );
}}
''',

            "src/pages/Dashboard.tsx": r'''
import React from "react";

import ProgressTracker from "../components/ProgressTracker";
import AIChat from "../components/AIChat";

export default function Dashboard() {

    return (
        <section>

            <h2>
                Dashboard
            </h2>

            <p>
                Generated by X337.
            </p>

            <ProgressTracker />

            <AIChat />

        </section>
    );
}
''',

            "src/pages/Practice.tsx": r'''
import React from "react";

import TaskPlanner from "../components/TaskPlanner";

export default function Practice() {

    return (
        <section>

            <h2>
                Practice
            </h2>

            <p>
                Personalized practice generated by X337.
            </p>

            <TaskPlanner />

        </section>
    );
}
''',

            "src/pages/Profile.tsx": r'''
import React from "react";

export default function Profile() {

    return (
        <section>

            <h2>
                Profile
            </h2>

            <p>
                Personalized learning profile.
            </p>

        </section>
    );
}
''',

            "src/components/ProgressTracker.tsx": r'''
import React from "react";

export default function ProgressTracker() {

    return (
        <div>

            <h3>
                Progress
            </h3>

            <p>
                Learning progress will appear here.
            </p>

        </div>
    );
}
''',

            "src/components/AIChat.tsx": r'''
import React from "react";

export default function AIChat() {

    return (
        <div>

            <h3>
                AI Tutor
            </h3>

            <p>
                Your X337 AI learning assistant.
            </p>

        </div>
    );
}
''',

            "src/components/TaskPlanner.tsx": r'''
import React from "react";

export default function TaskPlanner() {

    return (
        <div>

            <h3>
                Task Planner
            </h3>

            <p>
                Tasks generated by X337.
            </p>

        </div>
    );
}
'''
        }

        result = self.file_generator.create_project(
            safe_name,
            files
        )

        return {
            **result,
            "project": raw_name,
            "slug": safe_name
        }
