from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Dict, Optional


# ============================================================
# Parsed User Prompt
# ============================================================

@dataclass
class ParsedPrompt:
    """
    Raw information extracted from the user's request.
    """

    original: str

    project_name: str = ""

    description: str = ""

    keywords: List[str] = field(
        default_factory=list
    )

    project_type: str = ""

    style: str = ""

    domain: str = ""



# ============================================================
# User Intent
# ============================================================

@dataclass
class Intent:
    """
    Determines what the project requires.
    """

    frontend: bool = False

    backend: bool = False

    database: bool = False

    authentication: bool = False

    deployment: bool = False

    testing: bool = False

    documentation: bool = False

    api: bool = False

    website: bool = False

    dashboard: bool = False

    ai: bool = False



# ============================================================
# Technology Plan
# ============================================================

@dataclass
class TechnologyPlan:
    """
    Technology decisions generated by planner.
    """

    frontend_framework: str = "React"

    language: str = "TypeScript"

    styling: str = "Tailwind CSS"

    backend_framework: str = ""

    database: str = ""

    deployment: str = ""



# ============================================================
# Product Architecture Models
# ============================================================


@dataclass
class ProductWorkflow:
    """
    Represents a user journey.
    """

    name: str

    description: str



@dataclass
class DesignSystem:
    """
    AI-generated visual identity.
    """

    name: str = "Neural Glass"


    typography: Dict[str, str] = field(
        default_factory=lambda:
        {
            "heading": "Inter Bold",
            "body": "Inter Regular"
        }
    )


    colors: Dict[str, str] = field(
        default_factory=lambda:
        {
            "primary": "cyan",
            "background": "dark"
        }
    )


    component_style: str = (
        "modern glassmorphism"
    )


    animation_style: str = (
        "smooth AI motion"
    )



@dataclass
class ProductSpec:
    """
    Complete product definition.

    This replaces simple page generation
    with application intelligence.
    """

    name: str

    description: str


    category: str = ""


    user_goals: List[str] = field(
        default_factory=list
    )


    workflows: List[ProductWorkflow] = field(
        default_factory=list
    )


    features: List[str] = field(
        default_factory=list
    )


    design_system: DesignSystem = field(
        default_factory=DesignSystem
    )



# ============================================================
# Feature Specification
# ============================================================


@dataclass
class FeatureSpec:
    """
    Individual application capability.
    """

    name: str

    slug: str


    pages: List[str] = field(
        default_factory=list
    )


    components: List[str] = field(
        default_factory=list
    )


    backend_requirements: List[str] = field(
        default_factory=list
    )


    quality_requirements: List[str] = field(
        default_factory=list
    )



# ============================================================
# UI Planning Models
# ============================================================


@dataclass
class UIComponentSpec:
    """
    Component blueprint.
    """

    name: str

    component_type: str

    description: str


    props: Dict[str, str] = field(
        default_factory=dict
    )



@dataclass
class UIPageSpec:
    """
    Application page blueprint.
    """

    name: str

    route: str


    components: List[UIComponentSpec] = field(
        default_factory=list
    )


    layout: str = "default"



# ============================================================
# Final Planning Result
# ============================================================


@dataclass
class PlanningResult:
    """
    Complete output from planner pipeline.
    """

    parsed_prompt: ParsedPrompt


    intent: Intent


    technology_plan: TechnologyPlan = field(
        default_factory=TechnologyPlan
    )


    product_spec: Optional[ProductSpec] = None


    features: List[FeatureSpec] = field(
        default_factory=list
    )


    ui_pages: List[UIPageSpec] = field(
        default_factory=list
    )