import React from "react";

export default function Dashboard() {

    return (
        <div>

            <h2>Dashboard</h2>

            <p>
                Generated by X337.
            </p>

        </div>
    );
}
