import React from "react";

export default function Practice() {

    return (
        <div>

            <h2>Practice</h2>

            <p>
                Practice environment generated by X337.
            </p>

        </div>
    );
}
