
from fastapi import APIRouter

from api.schemas import User


router = APIRouter()



@router.get("/")
def home():

    return {

        "message":
        "Generated by X337"

    }



@router.post("/users")
def create_user(
    user: User
):

    return user
