def generate_fastapi_project():

    files = {


        "app.py": """

from fastapi import FastAPI


app = FastAPI(
    title="X337 Generated API"
)



@app.get("/")

def home():

    return {

        "message": "Generated by X337"

    }


@app.get("/users")

def users():

    return [

        {

            "id": 1,

            "name": "Example User"

        }

    ]



if __name__ == "__main__":

    import uvicorn


    uvicorn.run(

        app,

        host="0.0.0.0",

        port=8000

    )

""",


        "requirements.txt": """

fastapi
uvicorn

"""


    }


    return files
