def generate_react_project():

    files = {


        "App.jsx": """

export default function App(){

    return (

        <h1>
            Generated by X337
        </h1>

    );

}

"""

    }


    return files
