def generate_website():

    files = {


        "index.html": """

<!DOCTYPE html>

<html>

<head>

<title>X337 Website</title>

</head>


<body>


<h1>Generated by X337</h1>


<p>
AI created this website.
</p>


<script src="app.js"></script>


</body>

</html>

""",



        "app.js": """

console.log(
    "X337 website running"
);

"""


    }


    return files
