import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";

import {
    addTrainingExample,
    generateProject,
    getTrainingExamples,
} from "./api/generator";

import type {
    GenerateResponse,
    TrainingExample,
} from "./api/generator";
import "./App.css";

type Message = {
    role: "user" | "assistant";
    content: string;
};

type Tab = "chat" | "training" | "output";

export default function App() {
    const [tab, setTab] = useState<Tab>("chat");

    const [prompt, setPrompt] = useState("");
    const [messages, setMessages] = useState<Message[]>([
        {
            role: "assistant",
            content:
                "I’m X337. Describe the application you want me to build.",
        },
    ]);

    const [training, setTraining] = useState<TrainingExample[]>([]);
    const [trainingName, setTrainingName] = useState("");
    const [trainingDescription, setTrainingDescription] = useState("");
    const [trainingCode, setTrainingCode] = useState("");

    const [generation, setGeneration] =
        useState<GenerateResponse | null>(null);

    const [selectedFile, setSelectedFile] = useState("");
    const [loading, setLoading] = useState(false);
    const [trainingLoading, setTrainingLoading] = useState(false);
    const [error, setError] = useState("");

    useEffect(() => {
        getTrainingExamples()
            .then(setTraining)
            .catch((err) => {
                setError(String(err));
            });
    }, []);

    const generatedFileCount = generation?.files.length ?? 0;

    const selectedFileContent = useMemo(() => {
        if (!generation || !selectedFile) {
            return "";
        }

        return (
            `Generated artifact\n\n` +
            `Project: ${generation.project}\n` +
            `Path: ${selectedFile}\n\n` +
            `This file was generated by the canonical X337 React pipeline.`
        );
    }, [generation, selectedFile]);

    async function handleGenerate(
        event?: FormEvent,
    ) {
        event?.preventDefault();

        const trimmed = prompt.trim();

        if (!trimmed || loading) {
            return;
        }

        setError("");
        setLoading(true);

        setMessages((current) => [
            ...current,
            {
                role: "user",
                content: trimmed,
            },
            {
                role: "assistant",
                content:
                    "Planning the application, resolving architecture, composing the UI, and generating the React project…",
            },
        ]);

        try {
            const result = await generateProject(trimmed);

            setGeneration(result);

            setSelectedFile(result.files[0] ?? "");

            setMessages((current) => [
                ...current,
                {
                    role: "assistant",
                    content:
                        `Generation complete. ${result.files.length} files were created for ${result.project}.`,
                },
            ]);

            setTab("output");
            setPrompt("");
        } catch (err) {
            const message = String(err);

            setError(message);

            setMessages((current) => [
                ...current,
                {
                    role: "assistant",
                    content:
                        "Generation failed. Check the server output and try again.",
                },
            ]);
        } finally {
            setLoading(false);
        }
    }

    async function handleTraining(
        event: FormEvent,
    ) {
        event.preventDefault();

        if (
            !trainingName.trim() ||
            !trainingCode.trim() ||
            trainingLoading
        ) {
            return;
        }

        setTrainingLoading(true);
        setError("");

        try {
            const examples = await addTrainingExample({
                name: trainingName.trim(),
                description: trainingDescription.trim(),
                code: trainingCode,
            });

            setTraining(examples);
            setTrainingName("");
            setTrainingDescription("");
            setTrainingCode("");
        } catch (err) {
            setError(String(err));
        } finally {
            setTrainingLoading(false);
        }
    }

    return (
        <div className="x337-app">
            <header className="x337-topbar">
                <div className="x337-brand">
                    <div className="x337-logo">X</div>

                    <div>
                        <div className="x337-brand-title">
                            X337
                        </div>

                        <div className="x337-brand-subtitle">
                            AI Software Engineering Workspace
                        </div>
                    </div>
                </div>

                <div className="x337-status">
                    <span className="x337-status-dot" />
                    Generator Online
                </div>
            </header>

            <div className="x337-layout">
                <aside className="x337-sidebar">
                    <div className="x337-sidebar-label">
                        WORKSPACE
                    </div>

                    <button
                        className={
                            tab === "chat"
                                ? "x337-side-button active"
                                : "x337-side-button"
                        }
                        onClick={() => setTab("chat")}
                    >
                        <span>✦</span>
                        Build
                    </button>

                    <button
                        className={
                            tab === "training"
                                ? "x337-side-button active"
                                : "x337-side-button"
                        }
                        onClick={() => setTab("training")}
                    >
                        <span>◈</span>
                        Training
                    </button>

                    <button
                        className={
                            tab === "output"
                                ? "x337-side-button active"
                                : "x337-side-button"
                        }
                        onClick={() => setTab("output")}
                    >
                        <span>⌘</span>
                        Output
                    </button>

                    <div className="x337-sidebar-spacer" />

                    <div className="x337-training-summary">
                        <div className="x337-sidebar-label">
                            LEARNED REFERENCES
                        </div>

                        <strong>{training.length}</strong>

                        <span>
                            coding examples available
                        </span>
                    </div>
                </aside>

                <main className="x337-main">
                    {tab === "chat" && (
                        <section className="x337-panel x337-chat-panel">
                            <div className="x337-panel-heading">
                                <div>
                                    <span className="x337-eyebrow">
                                        BUILD WITH X337
                                    </span>

                                    <h1>
                                        What should we build?
                                    </h1>

                                    <p>
                                        Describe the product, behavior,
                                        visual style, and functionality.
                                    </p>
                                </div>
                            </div>

                            <div className="x337-chat-history">
                                {messages.map((message, index) => (
                                    <div
                                        key={index}
                                        className={
                                            message.role === "user"
                                                ? "x337-message user"
                                                : "x337-message assistant"
                                        }
                                    >
                                        <div className="x337-message-role">
                                            {message.role === "user"
                                                ? "YOU"
                                                : "X337"}
                                        </div>

                                        <div className="x337-message-content">
                                            {message.content}
                                        </div>
                                    </div>
                                ))}

                                {loading && (
                                    <div className="x337-generation-state">
                                        <span />
                                        <span />
                                        <span />
                                        Generating application…
                                    </div>
                                )}
                            </div>

                            <form
                                className="x337-prompt-box"
                                onSubmit={handleGenerate}
                            >
                                <textarea
                                    value={prompt}
                                    onChange={(event) =>
                                        setPrompt(event.target.value)
                                    }
                                    placeholder="Build a polished AI productivity application with..."
                                    rows={4}
                                    disabled={loading}
                                />

                                <div className="x337-prompt-footer">
                                    <span>
                                        {training.length} learned reference
                                        {training.length === 1 ? "" : "s"} will
                                        inform the workspace.
                                    </span>

                                    <button
                                        className="x337-primary-button"
                                        type="submit"
                                        disabled={
                                            loading || !prompt.trim()
                                        }
                                    >
                                        {loading
                                            ? "Building..."
                                            : "Generate Application →"}
                                    </button>
                                </div>
                            </form>
                        </section>
                    )}

                    {tab === "training" && (
                        <section className="x337-panel">
                            <div className="x337-panel-heading">
                                <div>
                                    <span className="x337-eyebrow">
                                        TRAIN X337
                                    </span>

                                    <h1>
                                        Teach X337 your style.
                                    </h1>

                                    <p>
                                        Paste a real implementation and
                                        describe what you want X337 to learn
                                        from it.
                                    </p>
                                </div>
                            </div>

                            <div className="x337-training-grid">
                                <form
                                    className="x337-training-form"
                                    onSubmit={handleTraining}
                                >
                                    <label>
                                        Reference name
                                        <input
                                            value={trainingName}
                                            onChange={(event) =>
                                                setTrainingName(
                                                    event.target.value,
                                                )
                                            }
                                            placeholder="Production SaaS dashboard"
                                        />
                                    </label>

                                    <label>
                                        What should X337 learn?
                                        <input
                                            value={trainingDescription}
                                            onChange={(event) =>
                                                setTrainingDescription(
                                                    event.target.value,
                                                )
                                            }
                                            placeholder="Component structure, spacing, interaction patterns..."
                                        />
                                    </label>

                                    <label>
                                        Reference code
                                        <textarea
                                            value={trainingCode}
                                            onChange={(event) =>
                                                setTrainingCode(
                                                    event.target.value,
                                                )
                                            }
                                            placeholder="Paste JSX, TSX, CSS, HTML, or another implementation..."
                                            rows={18}
                                        />
                                    </label>

                                    <button
                                        className="x337-primary-button"
                                        type="submit"
                                        disabled={
                                            trainingLoading ||
                                            !trainingName.trim() ||
                                            !trainingCode.trim()
                                        }
                                    >
                                        {trainingLoading
                                            ? "Learning..."
                                            : "Add Training Example"}
                                    </button>
                                </form>

                                <div className="x337-reference-list">
                                    <div className="x337-reference-header">
                                        <span>
                                            Learned references
                                        </span>

                                        <strong>
                                            {training.length}
                                        </strong>
                                    </div>

                                    {training.length === 0 && (
                                        <div className="x337-empty-state">
                                            No references yet.
                                        </div>
                                    )}

                                    {training.map((example, index) => (
                                        <article
                                            className="x337-reference-card"
                                            key={`${example.name}-${index}`}
                                        >
                                            <div className="x337-reference-card-top">
                                                <strong>
                                                    {example.name}
                                                </strong>

                                                <span>
                                                    REFERENCE
                                                </span>
                                            </div>

                                            <p>
                                                {example.description ||
                                                    "No description provided."}
                                            </p>

                                            <pre>
                                                {example.code.slice(0, 700)}
                                                {example.code.length > 700
                                                    ? "\n…"
                                                    : ""}
                                            </pre>
                                        </article>
                                    ))}
                                </div>
                            </div>
                        </section>
                    )}

                    {tab === "output" && (
                        <section className="x337-panel">
                            <div className="x337-panel-heading">
                                <div>
                                    <span className="x337-eyebrow">
                                        GENERATION OUTPUT
                                    </span>

                                    <h1>
                                        Application workspace
                                    </h1>

                                    <p>
                                        The result of X337's canonical
                                        planning and generation pipeline.
                                    </p>
                                </div>
                            </div>

                            {!generation && (
                                <div className="x337-empty-output">
                                    <div className="x337-empty-icon">
                                        ✦
                                    </div>

                                    <h2>
                                        No application generated yet
                                    </h2>

                                    <p>
                                        Start in Build and describe what you
                                        want X337 to create.
                                    </p>

                                    <button
                                        className="x337-primary-button"
                                        onClick={() => setTab("chat")}
                                    >
                                        Start Building
                                    </button>
                                </div>
                            )}

                            {generation && (
                                <div className="x337-output-grid">
                                    <div className="x337-output-sidebar">
                                        <div className="x337-output-project">
                                            <span>
                                                PROJECT
                                            </span>

                                            <strong>
                                                {generation.project}
                                            </strong>
                                        </div>

                                        <div className="x337-output-stat-row">
                                            <span>Files</span>
                                            <strong>
                                                {generatedFileCount}
                                            </strong>
                                        </div>

                                        <div className="x337-output-stat-row">
                                            <span>Pages</span>
                                            <strong>
                                                {generation.pages.length}
                                            </strong>
                                        </div>

                                        <div className="x337-output-stat-row">
                                            <span>Components</span>
                                            <strong>
                                                {generation.components.length}
                                            </strong>
                                        </div>

                                        <div className="x337-file-list">
                                            {generation.files.map(
                                                (file) => (
                                                    <button
                                                        key={file}
                                                        className={
                                                            selectedFile === file
                                                                ? "x337-file active"
                                                                : "x337-file"
                                                        }
                                                        onClick={() =>
                                                            setSelectedFile(
                                                                file,
                                                            )
                                                        }
                                                    >
                                                        {file}
                                                    </button>
                                                ),
                                            )}
                                        </div>
                                    </div>

                                    <div className="x337-output-content">
                                        <div className="x337-preview-card">
                                            <div className="x337-preview-header">
                                                <div>
                                                    <span className="x337-eyebrow">
                                                        LIVE APPLICATION
                                                    </span>

                                                    <h2>
                                                        Your application is running
                                                    </h2>

                                                    <p>
                                                        X337 generated the project
                                                        and started its live preview.
                                                    </p>
                                                </div>

                                                <a
                                                    className="x337-preview-link"
                                                    href={generation.preview.url}
                                                    target="_blank"
                                                    rel="noreferrer"
                                                >
                                                    Open Application ↗
                                                </a>
                                            </div>

                                            <div className="x337-preview-meta">
                                                <span>
                                                    ● {generation.preview.status}
                                                </span>

                                                <code>
                                                    {generation.preview.url}
                                                </code>
                                            </div>

                                            <div className="x337-preview-frame">
                                                <iframe
                                                    src={generation.preview.url}
                                                    title="X337 Generated Application Preview"
                                                    loading="lazy"
                                                />
                                            </div>
                                        </div>

                                        <div className="x337-output-editor">
                                            <div className="x337-editor-toolbar">
                                                <span>
                                                    {selectedFile ||
                                                        "Generated output"}
                                                </span>

                                                <span>
                                                    {generation.status}
                                                </span>
                                            </div>

                                            <pre>
                                                {selectedFileContent ||
                                                    "Select a generated file."}
                                            </pre>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </section>
                    )}

                    {error && (
                        <div className="x337-error">
                            {error}
                        </div>
                    )}
                </main>
            </div>
        </div>
    );
}
