import React from "react";

export default function TaskPlanner() {

    return (
        <div>

            <h3>Task Planner</h3>

            <p>
                Tasks generated by X337.
            </p>

        </div>
    );
}
