/**
 * Generated by X337
 *
 * Source:
 * unknown
 *
 * Origin:
 * unknown
 */

export default function Settings() {

  return (

    <main>

      <h1>
        Settings
      </h1>




    </main>

  );
}