
import React from "react";

import ProgressTracker from "../components/ProgressTracker";
import AIChat from "../components/AIChat";

export default function Dashboard() {

    return (
        <section>

            <h2>
                Dashboard
            </h2>

            <p>
                Generated by X337.
            </p>

            <ProgressTracker />

            <AIChat />

        </section>
    );
}
