from __future__ import annotations

from core.generators.generator_context import GeneratorContext
from core.generators.modules.base_module import BaseModule


class FeatureModule(BaseModule):
    """
    Establishes feature-level generation.

    Feature indexes, pages, and components are generated by
    their dedicated modules.
    """

    @property
    def name(self) -> str:
        return "features"

    def generate(
        self,
        context: GeneratorContext,
    ) -> None:

        # FeatureModule intentionally does not emit files.

        # FeatureIndexModule owns:
        #   features/<slug>/index.ts

        # FeaturePageModule owns:
        #   features/<slug>/pages/*

        # FeatureComponentModule owns:
        #   features/<slug>/components/*

        return
