from __future__ import annotations

from core.generators.generator_context import GeneratorContext
from core.generators.modules.base_module import BaseModule
from core.generators.react.page_naming import page_filename


class FeatureModule(BaseModule):
    """
    Generates feature-level entry points.

    FeatureSpec is the canonical feature representation.

    FeatureModule owns:
        frontend/src/features/<slug>/index.ts

    Feature pages and components are generated by their
    dedicated modules.
    """

    @property
    def name(self) -> str:
        return "features"

    def generate(
        self,
        context: GeneratorContext,
    ) -> None:
        for feature in context.spec.feature_models:
            if not feature.slug:
                continue

            page_filenames = []

            if context.spec.ui_spec:
                page_filenames = [
                    page_filename(page.name)
                    for page in context.spec.ui_spec.page_models
                    if page.metadata.get("feature")
                    == feature.slug
                ]

            context.builder.template(
                template="react/feature/index.ts.j2",
                output=(
                    f"frontend/src/features/"
                    f"{feature.slug}/index.ts"
                ),
                language="typescript",
                feature={
                    "slug": feature.slug,
                    "name": feature.name,
                    "pages": feature.pages,
                    "page_filenames": page_filenames,
                },
            )
