import os
from datetime import datetime


class ProjectGenerator:

    VERSION = "4.0.0"


    def __init__(self):

        self.base_path = "workspace/projects"



    # ---------------------------------
    # Main Generator
    # ---------------------------------

    def generate(
        self,
        project_name,
        task,
        plan=None
    ):


        project_path = os.path.join(
            self.base_path,
            project_name
        )


        os.makedirs(
            project_path,
            exist_ok=True
        )


        architecture = self.detect_architecture(
            task.title
        )


        blueprint = self.create_blueprint(
            architecture,
            plan
        )


        created_files = []


        for filename, content in blueprint.items():

            filepath = os.path.join(
                project_path,
                filename
            )


            directory = os.path.dirname(
                filepath
            )


            if directory:

                os.makedirs(
                    directory,
                    exist_ok=True
                )


            with open(
                filepath,
                "w"
            ) as file:

                file.write(content)


            created_files.append(
                filepath
            )



        metadata = {

            "project": project_name,

            "architecture": architecture,

            "version": self.VERSION,

            "generated": str(datetime.now()),

            "files": created_files

        }



        self.write_metadata(
            project_path,
            metadata
        )


        return {

            "name": project_name,

            "project": project_name,

            "architecture": architecture,

            "files": created_files,

            "metadata": metadata,

            "path": project_path

        }



    # ---------------------------------
    # Metadata
    # ---------------------------------

    def write_metadata(
        self,
        project_path,
        data
    ):

        import json


        with open(
            os.path.join(
                project_path,
                "x337.json"
            ),
            "w"
        ) as file:

            json.dump(
                data,
                file,
                indent=4
            )



    # ---------------------------------
    # Architecture Detection
    # ---------------------------------

    def detect_architecture(
        self,
        title
    ):


        title = title.lower()


        if "api" in title:

            return "fastapi"


        if "website" in title:

            return "website"


        if "agent" in title:

            return "ai_agent"



        return "python"



    # ---------------------------------
    # Blueprint Router
    # ---------------------------------

    def create_blueprint(
        self,
        architecture,
        plan=None
    ):


        if architecture == "fastapi":

            return self.fastapi()



        if architecture == "website":

            return self.website()



        if architecture == "ai_agent":

            return self.agent()



        return self.python()



    # ---------------------------------
    # FastAPI v4
    # ---------------------------------

    def fastapi(self):


        return {


"app.py":
"""
from fastapi import FastAPI
from api.routes import router


app = FastAPI(
    title="X337 Generated API"
)


app.include_router(router)
""",



"api/routes.py":
"""
from fastapi import APIRouter
from api.schemas import User


router = APIRouter()



@router.get("/")
def home():

    return {
        "message":
        "Generated by X337 v4"
    }



@router.post("/users")
def create_user(
    user: User
):

    return user
""",



"api/schemas.py":
"""
from pydantic import BaseModel



class User(BaseModel):

    name: str
""",



"services/service.py":
"""
def create_user(
    user
):

    return user
""",



"database/models.py":
"""
class UserModel:


    def __init__(
        self,
        name
    ):

        self.name = name
""",



"requirements.txt":
"""
fastapi
uvicorn
pydantic
""",



"README.md":
"""
# X337 Generated FastAPI Project v4

Run:

uvicorn app:app --reload
"""

        }



    # ---------------------------------
    # Website
    # ---------------------------------

    def website(self):


        return {


"index.html":
"""
<html>

<body>

<h1>
Generated by X337
</h1>

</body>

</html>
""",


"app.js":
"""
console.log(
"X337 Website Running"
)
""",


"style.css":
"""
body {

font-family: Arial;

}
"""

        }



    # ---------------------------------
    # AI Agent
    # ---------------------------------

    def agent(self):


        return {


"agent.py":
"""
class Agent:


    def execute(
        self,
        task
    ):

        return task
"""

        }



    # ---------------------------------
    # Python
    # ---------------------------------

    def python(self):


        return {


"main.py":
"""
print(
"Generated by X337"
)
"""

        }
