from core.generators.base_generator import BaseGenerator


class TemplateGenerator(BaseGenerator):

    def generate(self, task):

        return f'''"""
Generated by X337

Task:
{task.title}
"""

print("Task Completed!")
'''